from .config_controller import ConfigController
from .main_controller import MainWindowController
from .shortcut_controller import ShortcutController
from .scratch_pad_controller import ScratchPadController
